import Head from 'next/head';
import { BiPlus } from 'react-icons/bi';
import Form from './components/Form';

export default function Home() {
  return (
    <section>
      <Head>
        <title>Shopping List Application/</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='py-5'>
        <h1 className='text-xl md:text-5xl text-center font-bold py-10'>
          Shopping List
        </h1>

        <div className='container mx-auto flex justify-between py-5 border-b'>
          <div className='left flex gap-3'>
            <button className='flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-grary-50 hover:border-indigo-500 hover:text-gray-800'>
              <span className='px-1'>
                <BiPlus size={23}></BiPlus>
              </span>
              Add ShoppingList Item{' '}
            </button>
          </div>
        </div>
        {/* collapsable form */}
        <div className='container mx-auto py-5'>
          <Form></Form>
        </div>
      </main>
    </section>
  );
}
